### ISSUE TITLE
Ctrl-Cで抜けるとき、エラーを表示させないようにする

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/plsp#23]
Ctrl-Cすると次のようになる。
KeyboardInterruptを捉えてきちんと抜けるようにすればいいね。

plsp> Traceback (most recent call last):
  File "C:\Users\gamas\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gamas\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\gamas\AppData\Local\Programs\Python\Python310-32\Scripts\plsp.exe\__main__.py", line 7, in <module>
  File "C:\Users\gamas\AppData\Local\Programs\Python\Python310-32\lib\site-packages\plsp\plsp.py", line 11, in main
    repl_main()
  File "C:\Users\gamas\AppData\Local\Programs\Python\Python310-32\lib\site-packages\plsp\repl.py", line 16, in repl_main
    line = input(prompt if parentheses_count == 0 else "... ")

**Comment by gamasenninn** [comment]
解決
