### ISSUE TITLE
plspのパッケージ化

### ISSUE THREAD

**Issue by gamasenninn** [gamasenninn/plsp#9]
pip install git+https://github.com/gamasenninn/plsp.git
という形でインストールできるようにしたいのですが、どうしたらよいですか？

**Comment by gamasenninn** [comment]
chatGPT:
pipを使ってGitHubから直接インストールすることは可能です。ただし、そのためには、リポジトリにsetup.pyファイルを追加して、パッケージのメタデータや依存関係を指定する必要があります。以下に、setup.pyのサンプルを示します。

```python
# setup.py
from setuptools import setup, find_packages

setup(
    name='plsp',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        # 依存関係のあるパッケージをここに記述します。
    ],
    entry_points={
        'console_scripts': [
            'plsp = plsp:main',
        ],
    },
)
```
上記のsetup.pyをプロジェクトのルートディレクトリに追加し、さらにplsp.pyの内容を以下のように更新してmain関数を追加してください。

```python
# plsp.py
import sys
from repl import repl
from file_runner import run_file

def main():
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        run_file(filename)
    else:
        repl()

if __name__ == '__main__':
    main()
```
これで、次のようなコマンドを実行してGitHubから直接インストールすることができます。

```
pip install git+https://github.com/gamasenninn/plsp.git
```

注意: 上記のコマンドは、実際にインストールを行うものではありません。あなたのリポジトリURLに置き換えて実行してください。

これで、インストールが完了した後、plspコマンドが使えるようになります。pipでインストールされたパッケージは、仮想環境を使用して環境を分離することが推奨されます。

**Comment by gamasenninn** [comment]
だめだ。全然うまくいかん。

- エラー:
C:\Users\gamas>python -c "import plsp; print(plsp.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\onedrive\ドキュメント\plsp\plsp\__init__.py", line 1, in <module>
    from .plsp import main
  File "c:\onedrive\ドキュメント\plsp\plsp\plsp.py", line 3, in <module>
    from repl import repl_main
ModuleNotFoundError: No module named 'repl'

**Comment by gamasenninn** [comment]
chatGPT:

ChatGPT: 
- エラーの原因は、`plsp.py`内のインポート文で起こっています。`repl`と`file_runner`を相対インポートに変更する必要があります。そのため、`plsp.py`内のインポート文を次のように変更してください。

plsp.py:

```python
import sys
from .repl import repl_main
from .file_runner import run_file

def main():
    if len(sys.argv) > 1:
        filename = sys.argv[1]
        run_file(filename)
    else:
        repl_main()

if __name__ == '__main__':
    main()
```
この変更を加えた後、もう一度pipでパッケージをインストールし直してください。次に、再度 `import plsp`を試してエラーが解消されるか確認してください。

さらに、
ChatGPT: 
- `repl.py` ファイルで、`lparser`、`evaluator`、および `utils` といったモジュールをインポートしようとしていますが、相対インポートを使用していないため、エラーが発生しています。`repl.py` のインポート文を次のように修正してください。

repl.py:

```python
from .lparser import parse
from .evaluator import evaluate, initial_env
from .utils import schemestr
```
この変更を行った後、もう一度 pip でパッケージをインストールし直してください。次に、再度 `import plsp` を試してエラーが解消されるか確認してください。この変更で `lparser`、`evaluator`、および `utils` モジュールが正しくインポートされるはずです。

**Comment by gamasenninn** [comment]
このchatGPTの提案を參考にいろいろ試していたらできた。

**Comment by gamasenninn** [comment]
Person: 
- テストはうまくとおりました。import plspもできます。
ですが、python -m plspを実行すると次のエラーが出ます。

PS C:\OneDrive\ドキュメント\plsp> python -m plsp
C:\Users\gamas\AppData\Local\Programs\Python\Python311-32\python.exe: No module named plsp.__main__; 'plsp' is a package and cannot be directly executed

ChatGPT: 
- `python -m` を使用してパッケージを実行する場合、パッケージ内に `__main__.py` ファイルが必要です。このファイルは、パッケージがコマンドラインから実行された場合に実行されるエントリポイントとなります。

`plsp` パッケージ内に `__main__.py` ファイルを作成し、次のような内容を記述してください。

**main** .py:

```python
from .plsp import main

if __name__ == '__main__':
    main()
```



これで、`python -m plsp` を実行すると、`plsp` パッケージ内の `main()` 関数が呼び出されるようになります。

**Comment by gamasenninn** [comment]
Person: 
- では、コマンドとして実行するためには？

ChatGPT: 
- コマンドとして実行するためには、`setup.py` ファイルに `entry_points` を設定することで、インストール時にコマンドラインスクリプトを生成します。

まず、`setup.py` ファイルの `entry_points` を次のように設定します。

```python
setup(
    # 既存の設定は省略しています
    entry_points={
        'console_scripts': [
            'plsp = plsp.plsp:main',
        ],
    },
)
```



この設定により、`plsp.plsp` モジュール内の `main` 関数が `plsp` コマンドとして登録されます。

次に、変更を適用するためにパッケージを再インストールします。プロジェクトのルートディレクトリで、次のコマンドを実行してください。

```css
pip install --editable .
```



`--editable` オプションは、現在のプロジェクトディレクトリを参照しながらパッケージをインストールするために使用されます。これにより、プロジェクトの変更をリアルタイムで反映させることができます。

パッケージが再インストールされると、`plsp` コマンドが利用可能になります。コマンドプロンプトやターミナルで次のように実行してみてください。

```
plsp
```



これで、`plsp` パッケージがコマンドラインから直接実行できるようになります。

**Comment by gamasenninn** [comment]
開発環境とは別のマシンでも動いた
pip install git+https://github.com/gamasenninn/plsp.git

よってこのタスク完了
